version: '3.8'

services:
  autodeletebot:
    image: ghcr.io/count0ru/autodeletebot:latest
    container_name: autodeletebot-prod
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - CHANNEL_ID=${CHANNEL_ID}
      - USER_ID=${USER_ID}
      - USER_USERNAME=${USER_USERNAME}
      - DELETE_AFTER_MINUTES=${DELETE_AFTER_MINUTES:-86400}
      - CHECK_INTERVAL_MINUTES=${CHECK_INTERVAL_MINUTES:-720}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - LOG_FILE=/app/logs/bot.log
    volumes:
      - autodeletebot-data:/app/data
      - autodeletebot-logs:/app/logs
      - autodeletebot-config:/app/config
    ports:
      - "127.0.0.1:8080:8080"  # Bind only to localhost for security
    networks:
      - autodeletebot-prod-network
    healthcheck:
      test: ["CMD", "python3", "-c", "import sqlite3; sqlite3.connect('/app/data/messages.db')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  cleanup-cron:
    image: ghcr.io/count0ru/autodeletebot:latest
    container_name: autodeletebot-cleanup-prod
    restart: unless-stopped
    command: ["python3", "cleanup_script.py"]
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - CHANNEL_ID=${CHANNEL_ID}
      - USER_ID=${USER_ID}
      - USER_USERNAME=${USER_USERNAME}
      - DELETE_AFTER_MINUTES=${DELETE_AFTER_MINUTES:-86400}
      - CHECK_INTERVAL_MINUTES=${CHECK_INTERVAL_MINUTES:-720}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - LOG_FILE=/app/logs/cleanup.log
    volumes:
      - autodeletebot-data:/app/data
      - autodeletebot-logs:/app/logs
      - autodeletebot-config:/app/config
    networks:
      - autodeletebot-prod-network
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
        reservations:
          memory: 128M
          cpus: '0.1'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  autodeletebot-prod-network:
    driver: bridge
    name: autodeletebot-prod-network
    internal: true  # No external access

volumes:
  autodeletebot-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/autodeletebot/data
  autodeletebot-logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/autodeletebot/logs
  autodeletebot-config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/autodeletebot/config
